# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        arch: [ "arm64", "arm", "x64" ] # x86
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get SwiftShader
        uses: actions/checkout@v2
        with:
          path: 'swiftshader'

      - name: Build SwiftShader
        shell: bash
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=`pwd`/depot_tools:$PATH
          echo $PATH
          cd swiftshader
          cd build
          cmake ..
          export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export CC=clang
          export CXX=clang++
          cmake --build . --parallel

      - name: Upload ANGLE
        uses: actions/upload-artifact@v2
        with:
          name: angle-libs-${{matrix.arch}}
          path: |
            angle/out/Android-${{matrix.arch}}/libGLESv2_angle.so
            angle/out/Android-${{matrix.arch}}/libEGL_angle.so